version: '3.7'
services:
  app:
    build: .
    image: nodejs
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3000"
    networks:
      - my_network

networks:
  my_network:
