version: '3.7'
services:
  app:
    image: nodejs  # Usa el nombre de la imagen que has construido
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
